import type { RawWorkout, Workout, Exercise } from './types';
import { parseTiming, assertWorkout } from './timing';

const slugify = (text: string) => text.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]+/g, '');

const createExercise = (name: string): Exercise => ({
  name,
  image: `https://picsum.photos/seed/${slugify(name)}/400/400`,
  description: [
    'Maintain a straight back and engaged core.',
    'Focus on controlled, deliberate movements.',
    'Breathe steadily throughout the exercise.'
  ]
});

const WORKOUT_NAMES: RawWorkout[] = [
    // Cycles 1,2,3,4
    { cycle: "Cycle 1", week: "Week 1", day: "Monday", timing: "40/20", warmUp: "Crawling Warm Up", exercises: ["Parallel Leg Crunch", "Starfish Twist", "Stork Stance"], coolDown: "Spiderman A-Frames" },
    { cycle: "Cycle 1", week: "Week 1", day: "Wednesday", timing: "40/20", warmUp: "Crawling Warm Up", exercises: ["Parallel Leg Bridge", "Starfish Twist", "Stork Stance"], coolDown: "Spiderman A-Frames" },
    { cycle: "Cycle 1", week: "Week 1", day: "Friday", timing: "40/20", warmUp: "Crawling Warm Up", exercises: ["Arm Haulers", "Parallel Leg Crunch", "Parallel Leg Bridge"], coolDown: "Spiderman A-Frames" },
    { cycle: "Cycle 1", week: "Week 2", day: "Monday", timing: "40/20", warmUp: "Crawling Warm Up", exercises: ["Arm Haulers", "Starfish Twist", "Stork Stance"], coolDown: "Spiderman Arm Circles" },
    { cycle: "Cycle 1", week: "Week 2", day: "Wednesday", timing: "40/20", warmUp: "Crawling Warm Up", exercises: ["Parallel Leg Bridge", "Starfish Twist", "Bottom Squat"], coolDown: "Spiderman Arm Circles" },
    { cycle: "Cycle 1", week: "Week 2", day: "Friday", timing: "40/20", warmUp: "Crawling Warm Up", exercises: ["Arm Haulers", "Low Drop", "Stork Stance"], coolDown: "Spiderman Arm Circles" },
    { cycle: "Cycle 1", week: "Week 3", day: "Monday", timing: "45/15", warmUp: "Crawling Warm Up", exercises: ["Parallel Leg Crunch", "Starfish Twist", "High Knee March"], coolDown: "Bloomers" },
    { cycle: "Cycle 1", week: "Week 3", day: "Wednesday", timing: "45/15", warmUp: "Crawling Warm Up", exercises: ["Parallel Leg Bridge", "Low Drop", "High Knee March"], coolDown: "Bloomers" },
    { cycle: "Cycle 1", week: "Week 3", day: "Friday", timing: "45/15", warmUp: "Crawling Warm Up", exercises: ["Arm Haulers", "Kickout", "Bottom Squat"], coolDown: "Bloomers" },
    { cycle: "Cycle 1", week: "Week 4", day: "Monday", timing: "45/15", warmUp: "Crawling Warm Up", exercises: ["Parallel Leg Crunch", "Parallel Leg Bridge", "Arm Haulers"], coolDown: "Straddle Reach" },
    { cycle: "Cycle 1", week: "Week 4", day: "Wednesday", timing: "45/15", warmUp: "Crawling Warm Up", exercises: ["Bent Leg Bridge", "Starfish Twist", "Bottom Squat"], coolDown: "Straddle Reach" },
    { cycle: "Cycle 1", week: "Week 4", day: "Friday", timing: "45/15", warmUp: "Crawling Warm Up", exercises: ["Arm Haulers", "Low Drop", "Streamline RDL"], coolDown: "Straddle Reach" },
    { cycle: "Cycle 1", week: "Week 5", day: "Monday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Parallel Leg Crunch", "Kickout", "High Knee March"], coolDown: "Iso Pigeon Stretch" },
    { cycle: "Cycle 1", week: "Week 5", day: "Wednesday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Bent Leg Bridge", "Y Cuff", "Parallel Leg Crunch"], coolDown: "Iso Pigeon Stretch" },
    { cycle: "Cycle 1", week: "Week 5", day: "Friday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Arm Haulers", "Starfish Twist", "T-arm Squat"], coolDown: "Iso Pigeon Stretch" },
    { cycle: "Cycle 1", week: "Week 6", day: "Monday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Parallel Leg Crunch", "Kickout", "Bottom Squat"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 1", week: "Week 6", day: "Wednesday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Bent Leg Bridge", "High Kick", "Streamline RDL"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 1", week: "Week 6", day: "Friday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Y Cuff", "Bent Leg Crunch", "T-arm Squat"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 2", week: "Week 1", day: "Monday", timing: "40/20", warmUp: "Side Lying Warm Up", exercises: ["Arm Haulers", "Starfish Twist", "Stork Stance"], coolDown: "Spiderman A-Frames" },
    { cycle: "Cycle 2", week: "Week 1", day: "Thursday", timing: "40/20", warmUp: "Side Lying Warm Up", exercises: ["Bent Leg Bridge", "High Drop", "Bottom Squat"], coolDown: "Spiderman A-Frames" },
    { cycle: "Cycle 2", week: "Week 1", day: "Tuesday", timing: "40/20", warmUp: "Crawling Warm Up", exercises: ["Parallel Leg Bridge", "High Drop", "T-arm Squat"], coolDown: "Spiderman A-Frames" },
    { cycle: "Cycle 2", week: "Week 1", day: "Friday", timing: "40/20", warmUp: "Crawling Warm Up", exercises: ["Y Cuff", "High Kick", "High Knee Run"], coolDown: "Spiderman A-Frames" },
    { cycle: "Cycle 2", week: "Week 2", day: "Monday", timing: "40/20", warmUp: "Side Lying Warm Up", exercises: ["Arm Haulers", "Low Drop", "Streamline RDL"], coolDown: "Spiderman A-Frames" },
    { cycle: "Cycle 2", week: "Week 2", day: "Thursday", timing: "40/20", warmUp: "Side Lying Warm Up", exercises: ["Bent Leg Crunch", "Kickout", "Squat Thrust"], coolDown: "Spiderman A-Frames" },
    { cycle: "Cycle 2", week: "Week 2", day: "Tuesday", timing: "40/20", warmUp: "Crawling Warm Up", exercises: ["Bent Leg Bridge", "Starfish Drop", "High Knee March"], coolDown: "Spiderman A-Frames" },
    { cycle: "Cycle 2", week: "Week 2", day: "Friday", timing: "40/20", warmUp: "Crawling Warm Up", exercises: ["T-arm Reach", "Starfish Drop", "High Knee Run"], coolDown: "Bloomers" },
    { cycle: "Cycle 2", week: "Week 3", day: "Monday", timing: "45/15", warmUp: "Side Lying Warm Up", exercises: ["Arm Haulers", "Low Drop", "Streamline RDL"], coolDown: "Spiderman A-Frames" },
    { cycle: "Cycle 2", week: "Week 3", day: "Thursday", timing: "45/15", warmUp: "Side Lying Warm Up", exercises: ["Bent Leg Crunch", "Kickout", "Squat Thrust"], coolDown: "Spiderman A-Frames" },
    { cycle: "Cycle 2", week: "Week 3", day: "Tuesday", timing: "45/15", warmUp: "Crawling Warm Up", exercises: ["Bent Leg Bridge", "DF Glide", "Streamline RDL"], coolDown: "Spiderman A-Frames" },
    { cycle: "Cycle 2", week: "Week 3", day: "Friday", timing: "45/15", warmUp: "Crawling Warm Up", exercises: ["T-arm Reach", "High Drop", "T-arm Squat"], coolDown: "Bloomers" },
    { cycle: "Cycle 2", week: "Week 4", day: "Monday", timing: "45/15", warmUp: "Side Lying Warm Up", exercises: ["Arm Haulers", "Side Kick", "Stork Stance"], coolDown: "Spiderman A-Frames" },
    { cycle: "Cycle 2", week: "Week 4", day: "Thursday", timing: "45/15", warmUp: "Side Lying Warm Up", exercises: ["Bent Leg Crunch", "DF Glide", "Squat Thrust"], coolDown: "Spiderman A-Frames" },
    { cycle: "Cycle 2", week: "Week 4", day: "Tuesday", timing: "45/15", warmUp: "Crawling Warm Up", exercises: ["Bent Leg Bridge", "Starfish Drop", "Streamline RDL"], coolDown: "Spiderman A-Frames" },
    { cycle: "Cycle 2", week: "Week 4", day: "Friday", timing: "45/15", warmUp: "Crawling Warm Up", exercises: ["Y Cuff", "Double Drop", "Side Squat"], coolDown: "Iso Pigeon Stretch" },
    { cycle: "Cycle 2", week: "Week 5", day: "Monday", timing: "50/10", warmUp: "Side Lying Warm Up", exercises: ["Parallel Leg Bridge", "Kickout", "Side Squat"], coolDown: "Iso Pigeon Stretch" },
    { cycle: "Cycle 2", week: "Week 5", day: "Thursday", timing: "50/10", warmUp: "Side Lying Warm Up", exercises: ["Bent Leg Bridge", "Y Cuff", "Starfish Drop"], coolDown: "Straddle Reach" },
    { cycle: "Cycle 2", week: "Week 5", day: "Tuesday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["T-arm Reach", "High Kick", "Squat Thrust"], coolDown: "Iso Pigeon Stretch" },
    { cycle: "Cycle 2", week: "Week 5", day: "Friday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Arm Haulers", "Side Kick", "Drop Thrust"], coolDown: "Straddle Reach" },
    { cycle: "Cycle 2", week: "Week 6", day: "Monday", timing: "50/10", warmUp: "Side Lying Warm Up", exercises: ["Parallel Leg Bridge", "High Drop", "Side Squat"], coolDown: "Iso Pigeon Stretch" },
    { cycle: "Cycle 2", week: "Week 6", day: "Thursday", timing: "50/10", warmUp: "Side Lying Warm Up", exercises: ["Bent Leg Bridge", "Low Drop", "Bottom Squat"], coolDown: "Iso Pigeon Stretch" },
    { cycle: "Cycle 2", week: "Week 6", day: "Tuesday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Arm Haulers", "Side Kick", "Drop Thrust"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 2", week: "Week 6", day: "Friday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["T-arm Reach", "Kickout", "Drop Thrust"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 3", week: "Week 1", day: "Monday", timing: "40/20", warmUp: "Side Lying Warm Up", exercises: ["DF Glide", "Let Me Ins", "RDL-Squat"], coolDown: "A-Frames" },
    { cycle: "Cycle 3", week: "Week 1", day: "Tuesday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Straight Leg Bridge", "Side Kick", "Stork Stance"], coolDown: "Arm Circles" },
    { cycle: "Cycle 3", week: "Week 1", day: "Wednesday", timing: "50/10", warmUp: "Side Lying Warm Up", exercises: ["Straight Leg Crunch", "Starfish Drop", "T-arm Squat"], coolDown: "Straddle Reach" },
    { cycle: "Cycle 3", week: "Week 1", day: "Thursday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Bent Leg Crunch", "High Kick", "Squat Thrust"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 3", week: "Week 1", day: "Friday", timing: "40/20", warmUp: "Crawling Warm Up", exercises: ["DF Glide", "Let Me Ups", "Drop Thrust"], coolDown: "A-Frames" },
    { cycle: "Cycle 3", week: "Week 2", day: "Monday", timing: "50/10", warmUp: "Side Lying Warm Up", exercises: ["Arm Haulers", "Double Drop", "Parallel Leg Bridge"], coolDown: "A-Frames" },
    { cycle: "Cycle 3", week: "Week 2", day: "Tuesday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Straight Leg Bridge", "T-arm Reach", "Bottom Squat"], coolDown: "Arm Circles" },
    { cycle: "Cycle 3", week: "Week 2", day: "Wednesday", timing: "40/20", warmUp: "Side Lying Warm Up", exercises: ["Bent Leg Crunch", "High Drop", "Side Squat"], coolDown: "Straddle Reach" },
    { cycle: "Cycle 3", week: "Week 2", day: "Thursday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Y Cuff", "Starfish Twist", "Cossack"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 3", week: "Week 2", day: "Friday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Bent Leg Bridge", "Starfish Bounce", "T-arm Squat"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 3", week: "Week 3", day: "Monday", timing: "45/15", warmUp: "Side Lying Warm Up", exercises: ["Straight Leg Crunch", "Starfish Drop", "T-arm Squat"], coolDown: "A-Frames" },
    { cycle: "Cycle 3", week: "Week 3", day: "Tuesday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Bent Leg Bridge", "High Knee Run", "Stork Stance"], coolDown: "Arm Circles" },
    { cycle: "Cycle 3", week: "Week 3", day: "Wednesday", timing: "50/10", warmUp: "Side Lying Warm Up", exercises: ["Arm Haulers", "High Drop", "Straight Leg Bridge"], coolDown: "Straddle Reach" },
    { cycle: "Cycle 3", week: "Week 3", day: "Thursday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Y Cuff", "Dive Bomber", "Side Squat"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 3", week: "Week 3", day: "Friday", timing: "45/15", warmUp: "Crawling Warm Up", exercises: ["Bent Leg Crunch", "High Knee Skip", "Side Squat"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 3", week: "Week 4", day: "Monday", timing: "50/10", warmUp: "Side Lying Warm Up", exercises: ["DF Glide", "Tripod Let Me Ins", "Squat-RDL"], coolDown: "A-Frames" },
    { cycle: "Cycle 3", week: "Week 4", day: "Tuesday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Straight Leg Bridge", "High Kick", "T-arm Squat"], coolDown: "Arm Circles" },
    { cycle: "Cycle 3", week: "Week 4", day: "Wednesday", timing: "45/15", warmUp: "Side Lying Warm Up", exercises: ["Bent Leg Crunch", "Double Drop", "Squat-RDL"], coolDown: "Straddle Reach" },
    { cycle: "Cycle 3", week: "Week 4", day: "Thursday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Y Cuff", "Starfish Twist", "Cossack"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 3", week: "Week 4", day: "Friday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Bent Leg Bridge", "Starfish Bounce", "T-arm Squat"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 3", week: "Week 5", day: "Monday", timing: "50/10", warmUp: "Side Lying Warm Up", exercises: ["DF Glide", "Tripod Let Me Ups", "Squat-RDL"], coolDown: "A-Frames" },
    { cycle: "Cycle 3", week: "Week 5", day: "Tuesday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Straight Leg Bridge", "Side Kick", "RDL-Squat"], coolDown: "Arm Circles" },
    { cycle: "Cycle 3", week: "Week 5", day: "Wednesday", timing: "50/10", warmUp: "Side Lying Warm Up", exercises: ["Arm Haulers", "Double Drop", "Parallel Leg Bridge"], coolDown: "Straddle Reach" },
    { cycle: "Cycle 3", week: "Week 5", day: "Thursday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Y Cuff", "Dive Bomber", "Cossack"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 3", week: "Week 5", day: "Friday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Bent Leg Crunch", "High Knee Skip", "T-arm Squat"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 3", week: "Week 6", day: "Monday", timing: "50/10", warmUp: "Side Lying Warm Up", exercises: ["DF Glide", "Tripod Let Me Ups", "Squat-RDL"], coolDown: "A-Frames" },
    { cycle: "Cycle 3", week: "Week 6", day: "Tuesday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Straight Leg Bridge", "Side Kick", "RDL-Squat"], coolDown: "Arm Circles" },
    { cycle: "Cycle 3", week: "Week 6", day: "Wednesday", timing: "50/10", warmUp: "Side Lying Warm Up", exercises: ["Arm Haulers", "Double Drop", "Parallel Leg Bridge"], coolDown: "Straddle Reach" },
    { cycle: "Cycle 3", week: "Week 6", day: "Thursday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Y Cuff", "Dive Bomber", "Cossack"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 3", week: "Week 6", day: "Friday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Bent Leg Crunch", "High Knee Skip", "T-arm Squat"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 4", week: "Week 1", day: "Monday", timing: "60/0", warmUp: "Side Lying Warm Up", exercises: ["Starfish Drop", "Let Me Up", "T-arm Squat"], coolDown: "A-Frames" },
    { cycle: "Cycle 4", week: "Week 1", day: "Tuesday", timing: "40/20", warmUp: "Crawling Warm Up", exercises: ["Straight Leg Bridge", "High Kick", "Stork Stance"], coolDown: "Arm Circles" },
    { cycle: "Cycle 4", week: "Week 1", day: "Wednesday", timing: "60/0", warmUp: "Side Lying Warm Up", exercises: ["Double Drop", "AG Pull Up", "S2S Cossack"], coolDown: "Straddle Reach" },
    { cycle: "Cycle 4", week: "Week 1", day: "Thursday", timing: "40/20", warmUp: "Crawling Warm Up", exercises: ["Bent Leg Bridge", "Arm Haulers", "High Knee March"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 4", week: "Week 1", day: "Friday", timing: "60/0", warmUp: "Crawling Warm Up", exercises: ["Dive Bomber", "Let Me In", "T-arm Squat"], coolDown: "A-Frames" },
    { cycle: "Cycle 4", week: "Week 2", day: "Monday", timing: "40/20", warmUp: "Side Lying Warm Up", exercises: ["Straight Leg Crunch", "Starfish Twist", "High Knee Run"], coolDown: "Arm Circles" },
    { cycle: "Cycle 4", week: "Week 2", day: "Tuesday", timing: "40/20", warmUp: "Crawling Warm Up", exercises: ["Dive Bomber", "AG Pull Up", "SL BSS"], coolDown: "Straddle Reach" },
    { cycle: "Cycle 4", week: "Week 2", day: "Wednesday", timing: "60/0", warmUp: "Side Lying Warm Up", exercises: ["Bent Leg Bridge", "Low Drop", "High Knee Skip"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 4", week: "Week 2", day: "Thursday", timing: "60/0", warmUp: "Crawling Warm Up", exercises: ["DF Glide", "Tripod Let Me Ups", "SL RDL"], coolDown: "A-Frames" },
    { cycle: "Cycle 4", week: "Week 2", day: "Friday", timing: "40/20", warmUp: "Crawling Warm Up", exercises: ["T-arm Reach", "Straight Leg Bridge", "Parallel Leg Crunch"], coolDown: "Arm Circles" },
    { cycle: "Cycle 4", week: "Week 3", day: "Monday", timing: "60/0", warmUp: "Side Lying Warm Up", exercises: ["Tripod Press", "Let Me In", "RDL-Squat"], coolDown: "Straddle Reach" },
    { cycle: "Cycle 4", week: "Week 3", day: "Tuesday", timing: "45/15", warmUp: "Crawling Warm Up", exercises: ["Bent Leg Bridge", "High Drop", "Side Squat"], coolDown: "Iso Pigeon Stretch" },
    { cycle: "Cycle 4", week: "Week 3", day: "Wednesday", timing: "60/0", warmUp: "Side Lying Warm Up", exercises: ["T-arm Reach", "Kickout", "High Knee Skip"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 4", week: "Week 3", day: "Thursday", timing: "45/15", warmUp: "Crawling Warm Up", exercises: ["Bent Leg Crunch", "Side Kick", "RDL-Squat"], coolDown: "A-Frames" },
    { cycle: "Cycle 4", week: "Week 3", day: "Friday", timing: "60/0", warmUp: "Crawling Warm Up", exercises: ["Straight Leg Crunch", "High Knee Skip", "Drop Thrust"], coolDown: "Arm Circles" },
    { cycle: "Cycle 4", week: "Week 4", day: "Monday", timing: "45/15", warmUp: "Side Lying Warm Up", exercises: ["T-arm Reach", "Kickout", "High Knee Skip"], coolDown: "Straddle Reach" },
    { cycle: "Cycle 4", week: "Week 4", day: "Tuesday", timing: "60/0", warmUp: "Crawling Warm Up", exercises: ["Bent Leg Bridge", "High Drop", "Side Squat"], coolDown: "Iso Pigeon Stretch" },
    { cycle: "Cycle 4", week: "Week 4", day: "Wednesday", timing: "45/15", warmUp: "Side Lying Warm Up", exercises: ["DF Glide", "Let Me Ups", "Bottom Squat"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 4", week: "Week 4", day: "Thursday", timing: "60/0", warmUp: "Crawling Warm Up", exercises: ["Bent Leg Bridge", "Arm Haulers", "High Knee March"], coolDown: "A-Frames" },
    { cycle: "Cycle 4", week: "Week 4", day: "Friday", timing: "45/15", warmUp: "Crawling Warm Up", exercises: ["Straight Leg Crunch", "Side Kick", "RDL to Squat"], coolDown: "Arm Circles" },
    { cycle: "Cycle 4", week: "Week 5", day: "Monday", timing: "60/0", warmUp: "Side Lying Warm Up", exercises: ["Dive Bomber", "AG Pull Up", "SL BSS"], coolDown: "Straddle Reach" },
    { cycle: "Cycle 4", week: "Week 5", day: "Tuesday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["T-arm Squat", "High Knee Skip", "RDL-Squat"], coolDown: "Iso Pigeon Stretch" },
    { cycle: "Cycle 4", week: "Week 5", day: "Wednesday", timing: "60/0", warmUp: "Side Lying Warm Up", exercises: ["DF Glide", "Let Me Up", "SL RDL"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 4", week: "Week 5", day: "Thursday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Y Cuff", "Bent Leg Crunch", "T-arm Squat"], coolDown: "A-Frames" },
    { cycle: "Cycle 4", week: "Week 5", day: "Friday", timing: "60/0", warmUp: "Crawling Warm Up", exercises: ["Tripod Press", "AG Pull Up", "Stork Stance"], coolDown: "Arm Circles" },
    { cycle: "Cycle 4", week: "Week 6", day: "Monday", timing: "50/10", warmUp: "Side Lying Warm Up", exercises: ["T-arm Squat", "High Knee Skip", "RDL-Squat"], coolDown: "Straddle Reach" },
    { cycle: "Cycle 4", week: "Week 6", day: "Tuesday", timing: "60/0", warmUp: "Crawling Warm Up", exercises: ["DF Glide", "Let Me Up", "SL RDL"], coolDown: "Iso Pigeon Stretch" },
    { cycle: "Cycle 4", week: "Week 6", day: "Wednesday", timing: "50/10", warmUp: "Side Lying Warm Up", exercises: ["Arm Haulers", "Side Kick", "Squat-RDL"], coolDown: "Hip Rolls" },
    { cycle: "Cycle 4", week: "Week 6", day: "Thursday", timing: "60/0", warmUp: "Crawling Warm Up", exercises: ["Y Cuff", "Bent Leg Crunch", "T-arm Squat"], coolDown: "A-Frames" },
    { cycle: "Cycle 4", week: "Week 6", day: "Friday", timing: "50/10", warmUp: "Crawling Warm Up", exercises: ["Tripod Press", "AG Pull Up", "Stork Stance"], coolDown: "Arm Circles" },
];

export const BUILT_IN_DATA: Workout[] = WORKOUT_NAMES.map((w) => {
    const { work, rest, rounds } = parseTiming(w.timing, w.rounds);
    const id = `${w.cycle}|${w.week}|${w.day}|${w.timing}`.toLowerCase();

    // Omit the optional 'rounds' from the raw workout object before spreading
    const { rounds: _rawRounds, ...rawWorkoutRest } = w;

    return {
        ...rawWorkoutRest,
        id,
        work,
        rest,
        rounds,
        warmUp: createExercise(w.warmUp),
        exercises: w.exercises.map(createExercise),
        coolDown: createExercise(w.coolDown),
    };
}).filter(assertWorkout);