
/**
 * Map of Exercise Names to YouTube Video IDs.
 * Generated by Video Matcher Tool.
 */
export const exerciseYoutubeMap = new Map<string, string>([
  ['alternating grip pull ups', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['arm haulers', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['backstroke', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['bent leg bridge', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['bent leg crunch', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['bloomers', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['bottom squat', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['cossack squat', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['crawling warm up', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['dive bomber', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['double drop', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['double fun glide', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['drop thrust', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['high drop', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['high kick', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['high-knee march', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['high-knee run', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['high-knee skip', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['hip circles', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['hip rolls', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['itb leg lifts', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['iso pigeon stretch', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['jump thrust', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['jumping jacks', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['kickout', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['let me ins', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['let me ups', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['low drop', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['parallel leg bridge', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['parallel leg crunch', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['pointers', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['rdl to squat', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['side kick', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['side lying warm up', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['side squat', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['side to side cossack', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['side-lying leg lifts', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['spiderman a-frames', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['spiderman arm circles', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['squat thrust', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['squat to rdl', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['standing march', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['starfish bounce', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['starfish drop', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['starfish twist', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['stork stance', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['straddle reach', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['straight leg bridge', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['straight leg crunch', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['streamline bulgarien split squats', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['streamline rdl', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['t-arm reach', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['t-arm squat', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['tripod let me ups', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['tripod press', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['twist and reach', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
  ['y cuff', 'https://youtube.com/shorts/2NRBGYiDB9U?si=ZDDlW3MCb6PYitFc'],
]);

/**
 * Normalizes the name to ensure case-insensitive matching.
 */
const normalize = (name: string): string => name.toLowerCase().trim();

export const getYoutubeIdForExercise = (name: string): string | undefined => {
  return exerciseYoutubeMap.get(normalize(name));
};
