
import React, { useState, useMemo } from 'react';
import { BUILT_IN_DATA, CRAWLING_WARMUP_NAMES, SIDELYING_WARMUP_NAMES } from '../constants';
import { exerciseYoutubeMap } from '../services/exerciseVideoService';
import { BackArrowIcon, CheckIcon, YouTubeIcon } from './icons';

interface VideoMatcherProps {
    onBack: () => void;
}

export const VideoMatcher: React.FC<VideoMatcherProps> = ({ onBack }) => {
    // Collect all unique exercise names
    const allNames = useMemo(() => {
        const names = new Set<string>();
        
        // Add Warmups explicitely
        CRAWLING_WARMUP_NAMES.forEach(n => names.add(n));
        SIDELYING_WARMUP_NAMES.forEach(n => names.add(n));

        BUILT_IN_DATA.forEach(workout => {
            names.add(workout.preWarmUp.name);
            names.add(workout.warmUp.name);
            workout.warmUpExercises.forEach(ex => names.add(ex.name));
            workout.exercises.forEach(ex => names.add(ex.name));
            names.add(workout.coolDown.name);
        });
        
        return Array.from(names).sort();
    }, []);

    // Local state to store IDs
    const [ids, setIds] = useState<Record<string, string>>(() => {
        const initial: Record<string, string> = {};
        allNames.forEach(name => {
            const existingId = exerciseYoutubeMap.get(name.toLowerCase().trim());
            if (existingId) initial[name] = existingId;
        });
        return initial;
    });

    const [generatedCode, setGeneratedCode] = useState<string | null>(null);

    const handlePaste = (name: string, value: string) => {
        // Try to extract ID from URL
        let id = value.trim();
        const regExp = /(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/(?:watch\?v=|embed\/)|youtu\.be\/)([a-zA-Z0-9_-]{11})/;
        const match = value.match(regExp);
        
        if (match && match[1]) {
            id = match[1];
        }

        setIds(prev => ({ ...prev, [name]: id }));
    };

    const generateCode = () => {
        let code = `
/**
 * Map of Exercise Names to YouTube Video IDs.
 * Generated by Video Matcher Tool.
 */
export const exerciseYoutubeMap = new Map<string, string>([
`;

        allNames.forEach(name => {
            const id = ids[name] || '';
            code += `  ['${name.toLowerCase().trim()}', '${id}'],\n`;
        });

        code += `]);

/**
 * Normalizes the name to ensure case-insensitive matching.
 */
const normalize = (name: string): string => name.toLowerCase().trim();

export const getYoutubeIdForExercise = (name: string): string | undefined => {
  return exerciseYoutubeMap.get(normalize(name));
};
`;
        setGeneratedCode(code);
    };

    return (
        <div className="min-h-screen flex flex-col bg-black text-white">
            <header className="flex items-center p-4 border-b border-gray-800 bg-gray-900/50 sticky top-0 z-20 backdrop-blur-md">
                <button onClick={onBack} className="p-2 -ml-2 hover:bg-white/10 rounded-full transition-colors">
                    <BackArrowIcon className="w-6 h-6 text-white" />
                </button>
                <div className="mx-auto font-bold text-lg uppercase tracking-wider flex items-center gap-2">
                    <YouTubeIcon className="w-6 h-6 text-red-500" />
                    Video Matcher
                </div>
                <div className="w-6 h-6"></div>
            </header>

            {generatedCode ? (
                <div className="flex-grow p-4 flex flex-col">
                    <div className="bg-green-900/20 border border-green-500/50 p-4 rounded-lg mb-4 text-green-400 text-sm font-bold text-center">
                        Code Generated! Copy the text below and replace the content of <br/>
                        <code className="text-white bg-black/50 px-1 rounded">services/exerciseVideoService.ts</code>
                    </div>
                    <textarea 
                        className="flex-grow w-full bg-gray-900 font-mono text-xs text-green-400 p-4 rounded-xl border border-gray-700 focus:outline-none"
                        value={generatedCode}
                        readOnly
                    />
                    <div className="flex gap-4 mt-4">
                        <button 
                            onClick={() => setGeneratedCode(null)}
                            className="flex-1 bg-gray-800 text-white font-bold py-3 rounded-xl uppercase tracking-widest"
                        >
                            Back to Edit
                        </button>
                        <button 
                            onClick={() => { navigator.clipboard.writeText(generatedCode); alert('Copied to clipboard!'); }}
                            className="flex-1 bg-accent text-black font-bold py-3 rounded-xl uppercase tracking-widest"
                        >
                            Copy to Clipboard
                        </button>
                    </div>
                </div>
            ) : (
                <main className="flex-grow overflow-y-auto p-4 space-y-2">
                    <p className="text-gray-400 text-sm mb-4 bg-gray-900 p-3 rounded-lg border border-gray-800">
                        Paste full YouTube links into the fields. The ID will be extracted automatically.
                        When finished, click &quot;Generate Code&quot; at the bottom.
                    </p>
                    
                    {allNames.map((name) => (
                        <div key={name} className="flex flex-col gap-1 bg-gray-900/50 p-3 rounded-lg border border-gray-800">
                            <label className="text-xs font-bold text-gray-400 uppercase tracking-wide">{name}</label>
                            <div className="flex gap-2">
                                <input 
                                    type="text" 
                                    placeholder="Paste YouTube Link here..."
                                    className={`flex-grow bg-black text-white p-2 rounded border focus:outline-none text-sm font-mono ${ids[name] ? 'border-accent text-accent' : 'border-gray-700 text-gray-500'}`}
                                    value={ids[name] || ''}
                                    onChange={(e) => handlePaste(name, e.target.value)}
                                />
                                {ids[name] && <CheckIcon className="w-6 h-6 text-accent flex-shrink-0" />}
                            </div>
                        </div>
                    ))}

                    <div className="h-20"></div> {/* Spacer */}
                </main>
            )}

            {!generatedCode && (
                <footer className="p-4 border-t border-gray-800 bg-black sticky bottom-0 z-20">
                     <button 
                        onClick={generateCode}
                        className="w-full bg-accent text-black font-black py-4 rounded-xl uppercase tracking-widest shadow-[0_0_20px_rgba(74,222,128,0.3)]"
                    >
                        Generate Code File
                    </button>
                </footer>
            )}
        </div>
    );
};
